---
title: "OR538 Final Project - Step 2: Data Modeling"
output: html_notebook
---

# Modeling Paycheck Inc.

In this section we will be applying AR, MA, ARMA and ARIMA modeling for the PayCheck Inc. security and evaluating the models by using Ljung-Box Test on the residuals of each model.

## AR Modeling
Key points:
* Stationarity implies that the amount of variance is equal to the amount of feedback ($|\phi|<1$)
* $Y_t=(1-\phi)\mu+\phi{Y_{t-1}}+\epsilon_t$
* $Y_t=\beta_0+\beta_1{Y_t}+\epsilon_t$
* For model evalutation using Ljung-Box needs the fitdf parameter to be adjusted and its value depends on the AR model. For instance, for an AR(1) model the $fitdf=1$
* In the test a p-value of 0 indicates that at least one of the first **df** lags present an autocorrelation that is not zero

For each results plot residuals against time, ACF for the residuals and q-q plot using normal distribution for the errors (i.e. qqnorn).

any significant autocorrelation in the residuals implies that the model did not fit well.

One typical problem of AR(p) models is that they generally need a large number of p to fit the data set.

For the AR modeling we will be using the `auto.arima` function and setting the 
